# Generated by Django 3.2.6 on 2021-08-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyinfo',
            options={'verbose_name': '체형정보', 'verbose_name_plural': '체형정보'},
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='purpose',
            field=models.ManyToManyField(through='tags.PurposeTag', to='tags.HashTag'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='specialty',
            field=models.ManyToManyField(through='tags.SpecialtyTag', to='tags.HashTag'),
        ),
        migrations.AlterModelTable(
            name='bodyinfo',
            table='bodyinfo',
        ),
    ]
