# Generated by Django 3.2.5 on 2021-08-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oauth',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='OAuth_ID'),
        ),
    ]
