# Generated by Django 3.2.5 on 2021-08-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_oauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='oauth',
            new_name='oauth_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='oauth_type',
            field=models.CharField(choices=[('Google', 'google'), ('default', 'default')], default='default', max_length=10, verbose_name='OAuth_Type'),
        ),
    ]
