# Generated by Django 3.2.5 on 2021-08-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210804_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(upload_to='', verbose_name='프로필사진'),
        ),
    ]
