# Generated by Django 3.2.5 on 2021-08-21 12:45

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210815_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyinfo',
            name='body_type',
            field=models.CharField(choices=[('inverted_triangle', '역삼각형'), ('triangle', '삼각형'), ('leanRectangle', '빼빼로형'), ('wideRectangle', '통나무형'), ('oval', '복부비만'), ('default', '없음')], default='default', max_length=20, verbose_name='체형'),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='body_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to='users.bodyinfo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to=users.models.set_img_path, verbose_name='프로필사진'),
        ),
    ]
