# Generated by Django 3.2.5 on 2021-08-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        ('users', '0003_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to='centers.center'),
        ),
    ]
