# Generated by Django 3.2.5 on 2021-09-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('programs', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtytag',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coachprofile'),
        ),
        migrations.AddField(
            model_name='specialtytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.hashtag'),
        ),
        migrations.AddField(
            model_name='purposetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.hashtag'),
        ),
        migrations.AddField(
            model_name='purposetag',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.traineeprofile'),
        ),
        migrations.AddField(
            model_name='goaltag',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.goal'),
        ),
        migrations.AddField(
            model_name='goaltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.hashtag'),
        ),
    ]
