# Generated by Django 3.2.5 on 2021-10-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20211009_0651'),
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag_type',
            field=models.CharField(choices=[('default', 'default'), ('specialty', '전문성'), ('purpose', '목적')], default='default', max_length=20, verbose_name='태그 종류'),
        ),
        migrations.DeleteModel(
            name='GoalTag',
        ),
    ]
