# Generated by Django 3.2.5 on 2021-07-31 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=255, verbose_name='아침')),
                ('breakfast_clear', models.BooleanField(default=False, verbose_name='아침퀘스트 달성여부')),
                ('lunch', models.CharField(max_length=255, verbose_name='점심')),
                ('lunch_clear', models.BooleanField(default=False, verbose_name='아침퀘스트 달성여부')),
                ('dinner', models.CharField(max_length=255, verbose_name='저녁')),
                ('dinner_clear', models.BooleanField(default=False, verbose_name='아침퀘스트 달성여부')),
            ],
            options={
                'verbose_name': '식단',
                'verbose_name_plural': '식단',
                'db_table': 'meal_planner',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_content', models.TextField(verbose_name='운동퀘스트')),
                ('workout_clear', models.BooleanField(default=False, verbose_name='운동퀘스트 달성여부')),
            ],
            options={
                'verbose_name': '운동',
                'verbose_name_plural': '운동',
                'db_table': 'workout',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_feedback', models.TextField()),
                ('meal_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.mealplanner', verbose_name='식단퀘스트')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.workout', verbose_name='운동퀘스트')),
            ],
            options={
                'verbose_name': '퀘스트',
                'verbose_name_plural': '퀘스트',
                'db_table': 'quest',
            },
        ),
    ]
