# Generated by Django 3.2.5 on 2021-08-31 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=255, verbose_name='아침')),
                ('breakfast_clear', models.BooleanField(default=False, verbose_name='아침퀘스트 달성여부')),
                ('lunch', models.CharField(max_length=255, verbose_name='점심')),
                ('lunch_clear', models.BooleanField(default=False, verbose_name='아침퀘스트 달성여부')),
                ('dinner', models.CharField(max_length=255, verbose_name='저녁')),
                ('dinner_clear', models.BooleanField(default=False, verbose_name='아침퀘스트 달성여부')),
            ],
            options={
                'verbose_name': '식단',
                'verbose_name_plural': '식단',
                'db_table': 'meal_planner',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_content', models.TextField(verbose_name='운동퀘스트')),
                ('workout_clear', models.BooleanField(default=False, verbose_name='운동퀘스트 달성여부')),
            ],
            options={
                'verbose_name': '운동',
                'verbose_name_plural': '운동',
                'db_table': 'workout',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='퀘스트 생성일자')),
                ('rate_feedback', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='스탬프')),
                ('quest_feedback', models.TextField(default='', null=True, verbose_name='피드백')),
                ('meal_planner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.mealplanner', verbose_name='식단퀘스트')),
            ],
            options={
                'verbose_name': '퀘스트',
                'verbose_name_plural': '퀘스트',
                'db_table': 'quest',
            },
        ),
    ]
