# Generated by Django 3.2.5 on 2021-08-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='online_service',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='services.onlineservice', verbose_name='온라인 서비스'),
        ),
        migrations.AddField(
            model_name='quest',
            name='workout',
            field=models.ManyToManyField(to='quests.Workout', verbose_name='운동퀘스트'),
        ),
    ]
