# Generated by Django 3.2.6 on 2021-08-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='online_service',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='services.onlineservice', verbose_name='온라인 서비스'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='meal_planner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.mealplanner', verbose_name='식단퀘스트'),
        ),
        migrations.RemoveField(
            model_name='quest',
            name='workout',
        ),
        migrations.AddField(
            model_name='quest',
            name='workout',
            field=models.ManyToManyField(to='quests.Workout', verbose_name='운동퀘스트'),
        ),
    ]
