# Generated by Django 3.2.5 on 2021-08-11 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20210804_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='퀘스트 생성일자'),
        ),
        migrations.AddField(
            model_name='quest',
            name='rate_feedback',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='스탬프'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_feedback',
            field=models.TextField(default='', null=True, verbose_name='피드백'),
        ),
    ]
