# Generated by Django 3.2.5 on 2021-09-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20210913_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplanner',
            name='breakfast_clear',
        ),
        migrations.RemoveField(
            model_name='mealplanner',
            name='dinner_clear',
        ),
        migrations.RemoveField(
            model_name='mealplanner',
            name='lunch_clear',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_clear',
        ),
        migrations.AlterField(
            model_name='mealplanner',
            name='breakfast',
            field=models.JSONField(default={}, verbose_name='아침'),
        ),
        migrations.AlterField(
            model_name='mealplanner',
            name='dinner',
            field=models.JSONField(default={}, verbose_name='저녁'),
        ),
        migrations.AlterField(
            model_name='mealplanner',
            name='lunch',
            field=models.JSONField(default={}, verbose_name='점심'),
        ),
        migrations.RemoveField(
            model_name='quest',
            name='workout',
        ),
        migrations.AddField(
            model_name='quest',
            name='workout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.workout', verbose_name='운동퀘스트'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_content',
            field=models.JSONField(default={}, verbose_name='운동퀘스트'),
        ),
    ]
