# Generated by Django 3.2.5 on 2021-09-26 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, default=None, srid=4326, verbose_name='위치'),
        ),
    ]
