# Generated by Django 3.2.5 on 2021-09-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='text_goal',
        ),
        migrations.AddField(
            model_name='goal',
            name='tag',
            field=models.ManyToManyField(through='tags.GoalTag', to='tags.HashTag'),
        ),
    ]
