# Generated by Django 3.2.5 on 2021-08-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='term',
        ),
    ]
