# Generated by Django 3.2.6 on 2021-08-21 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='변경사유')),
                ('origin_date', models.DateField(verbose_name='기존수업 일자')),
                ('update_date', models.DateField(verbose_name='변경요청 일자')),
                ('requested_datetime', models.DateTimeField(auto_now_add=True, verbose_name='변경요청 시간')),
                ('fixed_date', models.DateTimeField(auto_now=True, verbose_name='요청승인 시간')),
                ('approval', models.BooleanField(default=False, verbose_name='승인여부')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='수업일자')),
                ('day_of_week', models.CharField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')], default=0, max_length=10, verbose_name='수업요일')),
                ('time', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='수업시간(30분_단위)')),
                ('reserved', models.BooleanField(default=False, verbose_name='예약여부')),
            ],
        ),
    ]
