# Generated by Django 3.2.5 on 2021-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='license',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='license',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='자격증'),
        ),
    ]
