# Generated by Django 3.2.5 on 2021-09-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coachprofile_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyinfo',
            options={'get_latest_by': ['created_at'], 'verbose_name': '체형정보', 'verbose_name_plural': '체형정보'},
        ),
        migrations.RenameField(
            model_name='bodyinfo',
            old_name='date',
            new_name='created_at',
        ),
    ]
