# Generated by Django 3.2.5 on 2021-10-01 08:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210922_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(default=datetime.date(2021, 9, 30), validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1984, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2021, 9, 30))], verbose_name='생년월일'),
        ),
    ]
