# Generated by Django 3.2.5 on 2021-10-04 14:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211001_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineeprofile',
            name='body_info',
        ),
        migrations.AddField(
            model_name='bodyinfo',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_info', to='users.traineeprofile'),
        ),
        migrations.AlterModelTable(
            name='bodyinfo',
            table='body_info',
        ),
    ]
