# Generated by Django 3.2.5 on 2021-10-06 13:17

import apps.users.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211004_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.set_img_path, verbose_name='프로필사진'),
        ),
    ]
