# Generated by Django 3.2.5 on 2021-10-08 04:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211006_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(default=datetime.date(2020, 1, 1), validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1984, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2021, 10, 7))], verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=150, verbose_name='닉네임'),
        ),
    ]
