# Generated by Django 3.2.5 on 2021-10-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20211013_1157'),
        ('users', '0008_auto_20211013_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_sms',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth.authsms', verbose_name='휴대폰 인증'),
        ),
    ]
