# Generated by Django 3.2.5 on 2021-09-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_rename_service_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='service',
            new_name='program',
        ),
        migrations.AlterModelTable(
            name='program',
            table='program',
        ),
    ]
