# Generated by Django 3.2.5 on 2021-10-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20210922_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='program',
            name='goal',
        ),
    ]
