# Generated by Django 3.2.5 on 2021-10-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20211009_0651'),
        ('programs', '0006_auto_20211009_0651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
