# Generated by Django 3.2.5 on 2021-10-13 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_delete_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='finished_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='started_date',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offlineclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offlineclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
