# Generated by Django 3.2.5 on 2021-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goaltag',
            old_name='goal_id',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='goaltag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='purposetag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='purposetag',
            old_name='trainee_id',
            new_name='trainee',
        ),
        migrations.RenameField(
            model_name='specialtytag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='specialtytag',
            old_name='trainer_id',
            new_name='trainer',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag_type',
            field=models.CharField(choices=[('specialty', '전문성'), ('purpose', '목적'), ('goal', '목표')], default=('specialty', '전문성'), max_length=20, verbose_name='태그 종류'),
        ),
    ]
