# Generated by Django 3.2.5 on 2021-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='quest_score',
        ),
        migrations.AddField(
            model_name='quest',
            name='meal_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='식단 달성률'),
        ),
        migrations.AddField(
            model_name='quest',
            name='workout_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='운동 달성률'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
