# Generated by Django 3.2.5 on 2021-09-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_auto_20210913_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='service',
            new_name='program',
        ),
    ]
