# Generated by Django 3.2.5 on 2021-09-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_auto_20210919_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='date',
            new_name='created_at',
        ),
    ]
