# Generated by Django 3.2.5 on 2021-09-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210913_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedulerequest',
            name='fixed_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='요청응답 시간'),
        ),
    ]
