# Generated by Django 3.2.5 on 2021-10-13 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210922_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='fixed_at',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
