# Generated by Django 3.2.5 on 2021-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=11, verbose_name='휴대폰 번호')),
                ('auth_number', models.IntegerField(max_length=4, verbose_name='인증번호')),
            ],
            options={
                'verbose_name': '휴대폰 인증',
                'verbose_name_plural': '휴대폰 인증',
                'db_table': 'auth_sms',
            },
        ),
        migrations.AlterModelOptions(
            name='auth',
            options={'verbose_name': 'OAuth 인증', 'verbose_name_plural': 'OAuth 인증'},
        ),
        migrations.AlterModelTable(
            name='auth',
            table='auth',
        ),
    ]
