# Generated by Django 3.2.5 on 2021-10-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20211013_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsms',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=11, null=True, verbose_name='휴대폰 번호'),
        ),
    ]
