# Generated by Django 3.2.5 on 2021-10-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_alter_authsms_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsms',
            name='validation',
            field=models.BooleanField(default=False, verbose_name='인증여부'),
        ),
    ]
