# Generated by Django 3.2.5 on 2021-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='full_address',
            field=models.CharField(max_length=100, verbose_name='도로명 주소'),
        ),
    ]
